### PR TITLE
fixes for 1.2 conformance testing

### PR DESCRIPTION
**Pull request by nkolba**
WIP - 3 more to go

### CODE REVIEW

**Comment by robmoffat** [comment]
I just checked out this code and tried to run it locally- all the basic tests are failing again.

**Comment by robmoffat** [comment]
seems to work best with the FINOS app directory, but I get lots of errors on the open tests now.   Silver lining is that it seems like a lot of the raise intent tests are definitely fixed, so well done there.

**Comment by nkolba** [comment]
@robmoffat   I am using the local directory in main branch of the conformance framework.  Are you on some other branch?

**Review by robmoffat — APPROVED** [review]
Suggest we remove `FDC3-Sail/directory/local-conformance-1_2.v2.json` as it is really out-of-date now.  Also maybe remove the conformance suite from the other directory json's too.  

Either we should run using the FINOS App Store (which currently works well for me with this PR) or the one in the Conformance project, which is also out-of-date and needs `inject-api` to be replaced with `injectApi` in the sail manifests

**Review by sebbenmbarek — APPROVED** [review]
LGTM
Also, looks like it fixes some concurrency issues with the directory

**Pull request merged**
