### PR TITLE
electron version update

### PR DESCRIPTION
**Pull request by nkolba**

### CODE REVIEW

**Review by robmoffat — APPROVED** [review]
Looks ok, but note ESLint is getting annoyed with you.

**Comment by robmoffat** [comment]
Also, @nkolba I am working on getting Sail to pass the 2.0 conformance tests.  Will have a PR completed mid October on this I think.

**Comment by nkolba** [comment]
Will fix the type issues.... @robmoffat  you may need to remind me what I need to do for EasyCLA at this point...

**Comment by robmoffat** [comment]
drop a mail to help@finos.org

**Pull request merged**
